import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "./tokens.stylex";

export const appStyles = stylex.create({
  appShell: {
    position: "relative",
    width: "100vw",
    height: {
      default: "100dvh",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    minHeight: "100dvh",
    display: {
      default: "block",
      "@media (max-width: 900px) and (max-height: 520px)": "flex",
    },
    flexDirection: "column",
    overflow: {
      default: "hidden",
      "@media (max-width: 900px) and (max-height: 520px)": "visible",
    },
    color: colors.text,
    backgroundColor: colors.canvas,
    backgroundImage: "radial-gradient(circle at 50% 46%, rgba(255, 255, 255, 0.018), transparent 38rem)",
    fontFamily: fonts.sans,
    fontSynthesis: "none",
  },
  skipLink: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    position: "fixed",
    top: 8,
    left: 8,
    zIndex: 40,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    borderRadius: 7,
    color: colors.canvas,
    backgroundColor: colors.text,
    fontSize: 11,
    fontWeight: 600,
    transform: {
      default: "translateY(-160%)",
      ":focus-visible": "translateY(0)",
    },
  },
  topToolbar: {
    position: {
      default: "fixed",
      "@media (max-width: 900px) and (max-height: 520px)": "relative",
    },
    top: {
      default: "calc(14px + env(safe-area-inset-top))",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-top))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    left: {
      default: "50%",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    zIndex: 20,
    maxWidth: "calc(100% - 16px)",
    overflowX: {
      default: "visible",
      "@media (max-width: 900px)": "auto",
    },
    scrollbarWidth: "none",
    height: {
      default: 38,
      "@media (max-width: 900px)": 52,
    },
    display: "flex",
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 6,
    transform: {
      default: "translateX(-50%)",
      "@media (max-width: 900px) and (max-height: 520px)": "none",
    },
    alignSelf: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "center",
    },
    order: 0,
    marginTop: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
    marginBottom: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
  },
  toolbarGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
  },
  toolbarButton: {
    flexShrink: 0,
    width: {
      default: 28,
      "@media (max-width: 900px)": 44,
    },
    height: {
      default: 28,
      "@media (max-width: 900px)": 44,
    },
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderRadius: 7,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    transform: {
      default: "none",
      ":active": "scale(0.96)",
    },
    transition: "transform 100ms ease",
  },
  toolbarSeparator: {
    width: 1,
    display: {
      default: "block",
      "@media (max-width: 900px)": "none",
    },
    height: 18,
    marginTop: 0,
    marginRight: 2,
    marginBottom: 0,
    marginLeft: 2,
    backgroundColor: colors.line,
  },
  mobileToolbarSeparator: {
    display: {
      default: "block",
      "@media (max-width: 900px)": "none",
    },
  },
  zoomOutput: {
    minWidth: 48,
    height: {
      default: 28,
      "@media (max-width: 900px)": 44,
    },
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
    borderRadius: 7,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    fontFamily: fonts.mono,
    fontSize: 11,
    lineHeight: 1,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
  },
  narrowZoomButton: {
    display: "grid",
  },
  layersPanel: {
    position: "fixed",
    top: "calc(64px + env(safe-area-inset-top))",
    left: "calc(14px + env(safe-area-inset-left))",
    zIndex: 15,
    width: 236,
    display: {
      default: "block",
      "@media (max-width: 900px)": "none",
    },
    overflow: "hidden",
  },
  layerList: {
    display: "grid",
    gap: 3,
    padding: 7,
  },
  layer: {
    width: "100%",
    minHeight: 48,
    display: "grid",
    gridTemplateColumns: "10px 30px minmax(0, 1fr)",
    alignItems: "center",
    gap: 7,
    paddingTop: 5,
    paddingRight: 9,
    paddingBottom: 5,
    paddingLeft: 5,
    borderColor: "transparent",
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      default: colors.textMuted,
      ":hover": colors.textSecondary,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": "rgba(255, 255, 255, 0.035)",
    },
    textAlign: "left",
    transform: {
      default: "none",
      ":active": "scale(0.993)",
    },
    transition: "transform 100ms ease",
  },
  activeLayer: {
    color: {
      default: colors.text,
      ":hover": colors.text,
    },
    borderColor: colors.line,
    backgroundColor: {
      default: colors.surfaceSelected,
      ":hover": colors.surfaceSelected,
    },
  },
  layerGrip: {
    color: "#4a4a51",
    fontFamily: fonts.mono,
    fontSize: 12,
    lineHeight: 1,
  },
  layerIcon: {
    width: 30,
    height: 30,
    display: "grid",
    placeItems: "center",
    borderColor: colors.line,
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.textSecondary,
    backgroundColor: "#19191b",
  },
  layerCopy: {
    minWidth: 0,
    display: "grid",
    gap: 3,
  },
  layerName: {
    overflow: "hidden",
    color: "inherit",
    fontSize: 12,
    fontWeight: 500,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  layerDetail: {
    overflow: "hidden",
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 9,
    lineHeight: 1,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  layersFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 10,
    paddingRight: 13,
    paddingBottom: 10,
    paddingLeft: 13,
    borderTopColor: colors.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: colors.textSecondary,
    fontSize: 10,
  },
  layersFooterDetail: {
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 8,
    lineHeight: 1,
    textTransform: "uppercase",
  },
  exportToolbar: {
    position: {
      default: "fixed",
      "@media (max-width: 900px) and (max-height: 520px)": "relative",
    },
    left: {
      default: "50%",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-left))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    right: {
      default: "auto",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-right))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    bottom: {
      default: "calc(14px + env(safe-area-inset-bottom))",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-bottom))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    zIndex: 20,
    height: {
      default: 40,
      "@media (max-width: 900px)": 52,
    },
    display: "flex",
    alignItems: "center",
    justifyContent: {
      default: "normal",
      "@media (max-width: 900px)": "center",
    },
    gap: 4,
    padding: 4,
    overflowX: {
      default: "visible",
      "@media (max-width: 900px)": "auto",
    },
    transform: {
      default: "translateX(-50%)",
      "@media (max-width: 900px)": "none",
    },
    width: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "calc(100% - 16px)",
    },
    maxWidth: "calc(100% - 16px)",
    alignSelf: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "center",
    },
    order: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 4,
    },
    marginTop: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
    marginBottom: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
  },
  exportButton: {
    minWidth: 44,
    height: {
      default: 30,
      "@media (max-width: 900px)": 44,
    },
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingTop: 0,
    paddingRight: {
      default: 9,
      "@media (max-width: 900px)": 6,
    },
    paddingBottom: 0,
    paddingLeft: {
      default: 9,
      "@media (max-width: 900px)": 6,
    },
    borderRadius: 7,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    fontSize: {
      default: 10,
      "@media (max-width: 900px)": 9,
    },
    whiteSpace: {
      default: "normal",
      "@media (max-width: 900px)": "nowrap",
    },
    transform: {
      default: "none",
      ":active": "scale(0.97)",
    },
    transition: "transform 100ms ease",
  },
  primaryExportButton: {
    paddingRight: {
      default: 12,
      "@media (max-width: 900px)": 8,
    },
    paddingLeft: {
      default: 12,
      "@media (max-width: 900px)": 8,
    },
    color: {
      default: "#171719",
      ":hover": "#0f0f10",
    },
    backgroundColor: {
      default: "#efefed",
      ":hover": "#ffffff",
    },
    fontWeight: 600,
  },
  fingerprint: {
    height: 27,
    display: {
      default: "inline-flex",
      "@media (max-width: 900px)": "none",
    },
    alignItems: "center",
    gap: 7,
    paddingTop: 0,
    paddingRight: 7,
    paddingBottom: 0,
    paddingLeft: 7,
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 9,
    lineHeight: 1,
  },
  fingerprintDot: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    backgroundColor: "#85858b",
  },
  toast: {
    position: {
      default: "fixed",
      "@media (max-width: 900px) and (max-height: 520px)": "sticky",
    },
    top: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": 0,
    },
    left: {
      default: "50%",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    bottom: {
      default: 66,
      "@media (min-height: 521px) and (min-width: 521px) and (max-width: 900px)": "calc(43dvh + 78px)",
      "@media (min-height: 521px) and (max-width: 520px)": "calc(46dvh + 78px)",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    zIndex: 30,
    minWidth: 230,
    maxWidth: "min(480px, calc(100vw - 32px))",
    minHeight: 38,
    maxHeight: {
      default: "none",
      "@media (max-width: 900px) and (max-height: 520px)": 60,
    },
    overflowY: {
      default: "visible",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingTop: 7,
    paddingRight: 8,
    paddingBottom: 7,
    paddingLeft: 13,
    borderColor: colors.lineStrong,
    borderRadius: 9,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.textSecondary,
    backgroundColor: colors.surface,
    boxShadow: "0 15px 36px rgba(0, 0, 0, 0.34)",
    fontSize: 10,
    transform: {
      default: "translateX(-50%)",
      "@media (max-width: 900px) and (max-height: 520px)": "none",
    },
    alignSelf: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "center",
    },
    order: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 1,
    },
    marginBottom: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
  },
  toastMessage: {
    minWidth: 0,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  toastButton: {
    width: {
      default: 24,
      "@media (max-width: 900px)": 44,
    },
    height: {
      default: 24,
      "@media (max-width: 900px)": 44,
    },
    flexShrink: 0,
    borderRadius: 5,
    color: {
      default: colors.textMuted,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    fontSize: 16,
  },
});
