import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "./tokens.stylex";

export const controlStyles = stylex.create({
  propertiesPanel: {
    position: {
      default: "fixed",
      "@media (max-width: 900px) and (max-height: 520px)": "relative",
    },
    top: {
      default: "calc(64px + env(safe-area-inset-top))",
      "@media (min-height: 521px) and (max-width: 900px)": "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    right: {
      default: "calc(14px + env(safe-area-inset-right))",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-right))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    bottom: {
      default: "calc(64px + env(safe-area-inset-bottom))",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(68px + env(safe-area-inset-bottom))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    left: {
      default: "auto",
      "@media (min-height: 521px) and (max-width: 900px)": "calc(8px + env(safe-area-inset-left))",
      "@media (max-width: 900px) and (max-height: 520px)": "auto",
    },
    zIndex: 15,
    width: {
      default: 278,
      "@media (min-height: 521px) and (max-width: 900px)": "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "calc(100% - 16px)",
    },
    maxHeight: {
      default: "none",
      "@media (min-height: 521px) and (min-width: 521px) and (max-width: 900px)": "43dvh",
      "@media (min-height: 521px) and (max-width: 520px)": "46dvh",
      "@media (max-width: 900px) and (max-height: 520px)": "none",
    },
    alignSelf: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "center",
    },
    order: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 3,
    },
    marginTop: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
    marginBottom: {
      default: 0,
      "@media (max-width: 900px) and (max-height: 520px)": 8,
    },
    display: "flex",
    flexDirection: "column",
    overflow: {
      default: "hidden",
      "@media (max-width: 900px) and (max-height: 520px)": "visible",
    },
  },
  mobilePanelTabs: {
    display: {
      default: "none",
      "@media (max-width: 900px)": "grid",
    },
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 3,
    padding: 5,
    borderBottomColor: colors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    backgroundColor: "#111113",
  },
  mobilePanelTab: {
    height: {
      default: 30,
      "@media (max-width: 900px)": 44,
    },
    borderRadius: 6,
    color: {
      default: colors.textMuted,
      ":hover": colors.textSecondary,
    },
    backgroundColor: "transparent",
    fontSize: 10,
    transition: "none",
  },
  activeMobilePanelTab: {
    color: {
      default: colors.text,
      ":hover": colors.text,
    },
    backgroundColor: colors.surfaceSelected,
  },
  propertiesScroll: {
    minHeight: 0,
    display: {
      default: "block",
      "@media (max-width: 900px)": "block",
    },
    overflowY: {
      default: "auto",
      "@media (max-width: 900px) and (max-height: 520px)": "visible",
    },
    overscrollBehavior: "contain",
    scrollbarWidth: "thin",
    scrollbarColor: "#3b3b41 transparent",
  },
  renderError: {
    marginTop: 10,
    marginRight: 12,
    marginBottom: 0,
    marginLeft: 12,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 170, 160, 0.4)",
    borderRadius: 7,
    color: "#ffc0b8",
    backgroundColor: "rgba(120, 24, 18, 0.28)",
    fontSize: 10,
    lineHeight: 1.4,
  },
  panelSection: {
    paddingTop: {
      default: 15,
      "@media (max-width: 900px)": 13,
    },
    paddingRight: {
      default: 14,
      "@media (max-width: 900px)": 13,
    },
    paddingBottom: {
      default: 17,
      "@media (max-width: 900px)": 13,
    },
    paddingLeft: {
      default: 14,
      "@media (max-width: 900px)": 13,
    },
    borderBottomColor: colors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
  },
  lastPanelSection: {
    borderBottomWidth: 0,
  },
  overline: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 13,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: "0.09em",
    textTransform: "uppercase",
  },
  recipeGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "1fr 1fr",
      "@media (min-width: 521px) and (max-width: 900px)": "repeat(4, minmax(100px, 1fr))",
      "@media (max-width: 520px)": "repeat(4, 112px)",
    },
    gap: 7,
    overflowX: {
      default: "visible",
      "@media (max-width: 900px)": "auto",
    },
    scrollbarWidth: {
      default: "auto",
      "@media (max-width: 900px)": "none",
    },
  },
  recipeButton: {
    minWidth: 0,
    display: "grid",
    gap: 5,
    padding: 6,
    borderColor: {
      default: colors.line,
      ":hover": colors.lineStrong,
    },
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "#18181a",
      ":hover": colors.surface,
    },
    textAlign: "left",
    transform: {
      default: "none",
      ":active": "scale(0.98)",
    },
    transition: "transform 100ms ease",
  },
  recipeName: {
    overflow: "hidden",
    paddingTop: 0,
    paddingRight: 2,
    paddingBottom: 0,
    paddingLeft: 2,
    fontSize: 10,
    fontWeight: 500,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  recipeDetail: {
    overflow: "hidden",
    paddingTop: 0,
    paddingRight: 2,
    paddingBottom: 2,
    paddingLeft: 2,
    color: colors.textMuted,
    fontSize: 8,
    lineHeight: 1.3,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  recipePreview: {
    height: 38,
    display: "block",
    overflow: "hidden",
    borderRadius: 5,
    backgroundColor: "#f7f6f3",
    backgroundSize: "10px 10px",
  },
  barsPreview: {
    backgroundImage: "repeating-linear-gradient(0deg, transparent 0 5px, rgba(20, 20, 20, 0.9) 5px 8px, transparent 8px 10px)",
  },
  candlesPreview: {
    backgroundImage: "repeating-linear-gradient(90deg, transparent 0 5px, rgba(110, 110, 112, 0.75) 5px 8px, transparent 8px 10px)",
  },
  shapesPreview: {
    backgroundImage: "radial-gradient(circle, rgba(235, 235, 235, 0.8) 0 2px, transparent 2.5px)",
  },
  segmented: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 3,
    marginBottom: 15,
    padding: 3,
    borderColor: colors.line,
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#111113",
  },
  compactSegmented: {
    marginTop: 13,
    marginBottom: 12,
  },
  segmentedButton: {
    minWidth: 0,
    height: {
      default: 28,
      "@media (max-width: 900px)": 44,
    },
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 0,
    paddingLeft: 5,
    borderRadius: 5,
    color: {
      default: colors.textMuted,
      ":hover": colors.textSecondary,
    },
    backgroundColor: "transparent",
    fontSize: 9,
    textTransform: "capitalize",
    transition: "none",
  },
  activeSegmentedButton: {
    color: {
      default: colors.text,
      ":hover": colors.text,
    },
    backgroundColor: colors.surfaceSelected,
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.035)",
  },
  propertyRow: {},
  stackedPropertyRow: {
    marginTop: 15,
  },
  propertyLabel: {
    minHeight: 24,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 7,
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  numberField: {
    height: {
      default: 26,
      "@media (max-width: 900px)": 46,
    },
    display: "inline-flex",
    alignItems: "center",
    overflow: "hidden",
    borderColor: colors.line,
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#19191b",
    outline: {
      default: "none",
      ":focus-within": "1px solid #ffffff",
    },
    outlineOffset: {
      default: 0,
      ":focus-within": 2,
    },
  },
  numberInput: {
    height: "100%",
    width: {
      default: 51,
      "@media (max-width: 900px)": 68,
    },
    minWidth: 0,
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 0,
    paddingLeft: 5,
    borderWidth: 0,
    outline: "none",
    color: colors.text,
    backgroundColor: "transparent",
    fontFamily: fonts.mono,
    fontSize: {
      default: 10,
      "@media (max-width: 900px)": 16,
    },
    lineHeight: 1,
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
    appearance: "textfield",
  },
  numberUnit: {
    paddingRight: 6,
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 9,
    lineHeight: 1,
  },
  rangeInput: {
    width: "100%",
    height: {
      default: 24,
      "@media (max-width: 900px)": 44,
    },
    display: "block",
    margin: 0,
    appearance: "none",
    backgroundColor: "transparent",
    cursor: "ew-resize",
  },
  toggleRow: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  toggleAfterProperty: {
    marginTop: 10,
  },
  toggleAfterDimensions: {
    marginTop: 14,
  },
  switch: {
    width: 44,
    height: 44,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    padding: 0,
    backgroundColor: "transparent",
  },
  switchTrack: {
    width: 31,
    height: 18,
    display: "block",
    padding: 2,
    borderColor: {
      default: colors.lineStrong,
      ":hover": "rgba(255, 255, 255, 0.34)",
    },
    borderRadius: 18,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#111113",
  },
  activeSwitch: {
    borderColor: "#77777e",
    backgroundColor: "#3b3b40",
  },
  switchThumb: {
    width: 12,
    height: 12,
    display: "block",
    borderRadius: "50%",
    backgroundColor: "#72727a",
    transform: "none",
    transition: "transform 140ms ease",
  },
  activeSwitchThumb: {
    transform: "translateX(13px)",
    backgroundColor: "#f0f0f2",
  },
  selectControl: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  select: {
    minWidth: 118,
    height: {
      default: 29,
      "@media (max-width: 900px)": 44,
    },
    paddingTop: 0,
    paddingRight: 24,
    paddingBottom: 0,
    paddingLeft: 8,
    borderColor: {
      default: colors.line,
      ":hover": colors.lineStrong,
    },
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "#1d1d20",
      ":hover": colors.surfaceHover,
    },
    fontSize: {
      default: 10,
      "@media (max-width: 900px)": 16,
    },
  },
  colorList: {
    display: "grid",
    gap: 5,
    marginTop: 8,
  },
  colorRow: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    color: colors.textSecondary,
    fontSize: 10,
  },
  colorInput: {
    width: 46,
    height: {
      default: 25,
      "@media (max-width: 900px)": 44,
    },
    padding: 3,
    borderColor: {
      default: colors.line,
      ":hover": colors.lineStrong,
    },
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#111113",
    cursor: "pointer",
  },
  sourceSummary: {
    display: "grid",
    gridTemplateColumns: "36px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
  },
  sourceIcon: {
    width: 36,
    height: 36,
    display: "grid",
    placeItems: "center",
    borderColor: colors.line,
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.textSecondary,
    backgroundColor: colors.surface,
  },
  sourceCopy: {
    minWidth: 0,
    display: "grid",
    gap: 4,
  },
  sourceName: {
    overflow: "hidden",
    fontSize: 11,
    fontWeight: 500,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sourceDetail: {
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 8,
    lineHeight: 1,
  },
  sourceButton: {
    height: {
      default: 27,
      "@media (max-width: 900px)": 44,
    },
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderColor: {
      default: colors.line,
      ":hover": colors.lineStrong,
    },
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: colors.surface,
    fontSize: 9,
  },
  helperCopy: {
    marginTop: 9,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textMuted,
    fontSize: 10,
    lineHeight: 1.55,
    textWrap: "pretty",
  },
  dimensionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  dimensionLabel: {
    display: "grid",
    gap: 7,
  },
  dimensionInput: {
    width: "100%",
    height: 25,
    display: "inline-flex",
    alignItems: "center",
    overflow: "hidden",
    borderColor: colors.line,
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: "#19191b",
    outline: {
      default: "none",
      ":focus-within": "1px solid #ffffff",
    },
    outlineOffset: {
      default: 0,
      ":focus-within": 2,
    },
  },
  dimensionNumberInput: {
    width: "100%",
    minWidth: 0,
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 0,
    paddingLeft: 5,
    borderWidth: 0,
    outline: "none",
    color: colors.text,
    backgroundColor: "transparent",
    fontFamily: fonts.mono,
    fontSize: 10,
    lineHeight: 1,
    textAlign: "left",
    fontVariantNumeric: "tabular-nums",
    appearance: "textfield",
  },
  dimensionUnit: {
    paddingRight: 6,
    color: colors.textMuted,
    fontFamily: fonts.mono,
    fontSize: 9,
    lineHeight: 1,
  },
});
