import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "./tokens.stylex";

export const exportMenuStyles = stylex.create({
  trigger: {
    height: { default: 30, "@media (max-width: 900px)": 44 },
    minWidth: 44,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingTop: 0,
    paddingRight: 12,
    paddingBottom: 0,
    paddingLeft: 12,
    borderRadius: 7,
    color: "#000000",
    backgroundColor: { default: "#efefed", ":hover": "#ffffff", ":active": "#dddddd" },
    fontFamily: fonts.sans,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.35,
    whiteSpace: "nowrap",
    touchAction: "manipulation",
    outline: { default: "none", ":focus-visible": "2px solid #ffffff" },
    outlineOffset: 3,
  },
  dialog: {
    position: "fixed",
    inset: 0,
    width: "min(620px, calc(100vw - 32px - env(safe-area-inset-left) - env(safe-area-inset-right)))",
    height: "fit-content",
    maxHeight: "calc(100dvh - 32px - env(safe-area-inset-top) - env(safe-area-inset-bottom))",
    margin: "auto",
    padding: 0,
    overflow: "hidden",
    overscrollBehavior: "contain",
    borderColor: colors.lineStrong,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 12,
    color: colors.text,
    backgroundColor: { default: colors.panelSolid, "::backdrop": "rgba(0, 0, 0, 0.48)" },
    fontFamily: fonts.sans,
    fontSize: 14,
    lineHeight: 1.5,
    colorScheme: "dark",
  },
  openDialog: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
  },
  header: {
    display: "grid",
    gap: 8,
    padding: 16,
    borderBottomColor: colors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
  },
  title: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    lineHeight: 1.3,
    textWrap: "balance",
    scrollMarginTop: 16,
  },
  copy: {
    margin: 0,
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  body: {
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: 16,
    scrollbarWidth: "thin",
    scrollbarColor: "#44444a transparent",
  },
  fieldset: {
    minWidth: 0,
    margin: 0,
    padding: 0,
    borderWidth: 0,
  },
  legend: {
    marginBottom: 12,
    padding: 0,
    fontSize: 14,
    fontWeight: 600,
  },
  formatGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    overflow: "hidden",
    borderTopColor: colors.lineStrong,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    borderLeftColor: colors.lineStrong,
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    borderRadius: 8,
  },
  formatChoice: {
    minWidth: 0,
    minHeight: 44,
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr)",
    alignContent: "start",
    gap: 10,
    padding: 12,
    borderRightColor: colors.lineStrong,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    borderBottomColor: colors.lineStrong,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    backgroundColor: { default: colors.panelSolid, ":hover": colors.surfaceHover },
    cursor: "pointer",
    touchAction: "manipulation",
    outline: { default: "none", ":focus-within": "2px solid #ffffff" },
    outlineOffset: -3,
  },
  selectedChoice: {
    backgroundColor: { default: colors.surfaceSelected, ":hover": colors.surfaceHover },
  },
  unavailableChoice: {
    color: colors.textSecondary,
    cursor: "not-allowed",
  },
  projectChoice: {
    gridColumn: "1 / -1",
  },
  radio: {
    width: 16,
    height: 16,
    marginTop: 3,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    accentColor: "#ffffff",
  },
  choiceCopy: {
    minWidth: 0,
    display: "grid",
    gap: 4,
  },
  formatName: {
    fontSize: 14,
    fontWeight: 600,
    overflowWrap: "anywhere",
  },
  reason: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  settings: {
    marginTop: 20,
  },
  settingsGrid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", "@media (max-width: 520px)": "minmax(0, 1fr)" },
    gap: 16,
    alignItems: "start",
  },
  field: {
    minWidth: 0,
    display: "grid",
    gap: 8,
    fontSize: 14,
  },
  numberField: {
    minWidth: 0,
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    borderColor: colors.lineStrong,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 7,
    outline: { default: "none", ":focus-within": "2px solid #ffffff" },
    outlineOffset: 2,
  },
  numberInput: {
    width: "100%",
    minWidth: 0,
    minHeight: 44,
    padding: 10,
    borderWidth: 0,
    borderRadius: 7,
    outline: "none",
    color: colors.text,
    backgroundColor: colors.surface,
    fontFamily: fonts.sans,
    fontSize: 14,
    lineHeight: 1.5,
    fontVariantNumeric: "tabular-nums",
  },
  unit: {
    flexShrink: 0,
    paddingRight: 12,
    color: colors.textSecondary,
    fontSize: 14,
  },
  colorField: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  colorInput: {
    width: 64,
    height: 44,
    flexShrink: 0,
    padding: 4,
    borderColor: colors.lineStrong,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 7,
    backgroundColor: colors.surface,
    cursor: "pointer",
    outline: { default: "none", ":focus-visible": "2px solid #ffffff" },
    outlineOffset: 2,
  },
  colorValue: {
    minWidth: 0,
    fontFamily: fonts.sans,
    fontSize: 14,
    fontVariantNumeric: "tabular-nums",
  },
  help: {
    marginTop: 12,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  error: {
    marginTop: 8,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: "#ffb4a8",
    fontSize: 14,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    textWrap: "pretty",
  },
  exportError: {
    marginTop: 16,
  },
  footer: {
    display: "grid",
    gap: 12,
    padding: 16,
    borderTopColor: colors.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
  },
  progressGroup: {
    display: "grid",
    gap: 8,
    fontVariantNumeric: "tabular-nums",
  },
  progress: {
    width: "100%",
    height: 8,
    display: "block",
    accentColor: "#ffffff",
  },
  actions: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  primaryButton: {
    minWidth: 0,
    minHeight: 44,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    borderRadius: 7,
    color: "#000000",
    backgroundColor: { default: "#efefed", ":hover": "#ffffff", ":active": "#dddddd" },
    fontFamily: fonts.sans,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.35,
    touchAction: "manipulation",
    outline: { default: "none", ":focus-visible": "2px solid #ffffff" },
    outlineOffset: 3,
  },
  secondaryButton: {
    minWidth: 0,
    minHeight: 44,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    borderColor: colors.lineStrong,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 7,
    color: colors.text,
    backgroundColor: { default: colors.surface, ":hover": colors.surfaceHover, ":active": colors.surfaceSelected },
    fontFamily: fonts.sans,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: 1.35,
    touchAction: "manipulation",
    outline: { default: "none", ":focus-visible": "2px solid #ffffff" },
    outlineOffset: 3,
  },
});
