import * as stylex from "@stylexjs/stylex";
import { colors } from "./tokens.stylex";

export const selectStyles = stylex.create({
  field: {
    minHeight: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  stackedField: {
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    alignItems: "stretch",
    justifyContent: "normal",
    gap: 7,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  trigger: {
    minWidth: 118,
    maxWidth: "65%",
    height: { default: 29, "@media (max-width: 900px)": 44 },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderColor: { default: colors.line, ":hover": colors.lineStrong },
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 6,
    color: { default: colors.textSecondary, ":hover": colors.text },
    backgroundColor: { default: "#1d1d20", ":hover": colors.surfaceHover },
    fontSize: { default: 10, "@media (max-width: 900px)": 16 },
    textAlign: "left",
  },
  stackedTrigger: {
    width: "100%",
    minWidth: 0,
    maxWidth: "none",
  },
  value: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chevron: {
    flexShrink: 0,
    color: colors.textMuted,
  },
  menu: {
    position: "fixed",
    zIndex: 1000,
    boxSizing: "border-box",
    overflowY: "auto",
    overscrollBehavior: "contain",
    touchAction: "pan-y",
    padding: 4,
    borderColor: colors.lineStrong,
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 8,
    backgroundColor: "#18181a",
    boxShadow: "0 12px 36px rgba(0, 0, 0, 0.45)",
    scrollbarWidth: "thin",
    scrollbarColor: "#3b3b41 transparent",
  },
  option: {
    minHeight: { default: 32, "@media (max-width: 900px)": 44 },
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingTop: 5,
    paddingRight: 8,
    paddingBottom: 5,
    paddingLeft: 8,
    borderRadius: 5,
    color: colors.textSecondary,
    fontSize: { default: 11, "@media (max-width: 900px)": 14 },
    cursor: "pointer",
  },
  activeOption: {
    color: colors.text,
    backgroundColor: colors.surfaceSelected,
  },
  disabledOption: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
  check: {
    width: 14,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
});
