import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "./tokens.stylex";

export const sharedStyles = stylex.create({
  glassPanel: {
    borderColor: colors.lineStrong,
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: colors.panel,
    boxShadow: "0 14px 36px rgba(0, 0, 0, 0.28), inset 0 1px rgba(255, 255, 255, 0.025)",
    backdropFilter: "blur(22px) saturate(120%)",
  },
  panelHeader: {
    minHeight: 42,
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    gap: 8,
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 14,
    borderBottomColor: colors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  panelHeaderButton: {
    width: 28,
    height: 28,
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderRadius: 7,
    color: {
      default: colors.textSecondary,
      ":hover": colors.text,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surfaceHover,
    },
    transform: {
      default: "none",
      ":active": "scale(0.96)",
    },
    transition: "transform 100ms ease",
  },
  panelHeaderSmall: {
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 6,
    borderRadius: 5,
    color: colors.textMuted,
    backgroundColor: colors.surface,
    fontFamily: fonts.mono,
    fontSize: 9,
    lineHeight: 1,
    letterSpacing: 0,
    textTransform: "none",
  },
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
